name: hsma5_forecast
channels:
  - conda-forge
dependencies:
  - ipywidgets=7.6.5
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab=3.2.4
  - matplotlib=3.5.0
  - notebook=6.0.3
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.0.1
  - plotly=5.4.0
  - python=3.8.8
  - scipy=1.7.3
  - seaborn=0.11.2
  - statsmodels=0.11.1
  - pip:
    - forecast-tools==0.1.6
    - prophet==1.0.1
    - pystan==2.19.1.1
    - scikit-learn==1.0.1

